### ISSUE TITLE
 Multiprocess application metrics endpoint is taking more time to respond

### ISSUE THREAD

**Issue by Velan987** [rycus86/prometheus_flask_exporter#132]
I have a multiprocess enabled application, I am able to expose /metrics api successfully. When I start the server /metrics api is responding within 1second, after few hours it is taking more time (more than one minute). Can someone please help me on debugging this issue.

**Comment by rycus86** [comment]
Can you share your app and/or its setup to help reproducing the issue?

**Comment by Velan987** [comment]
os.environ["PROMETHEUS_MULTIPROC_DIR"]='/tmp'

app = Flask(name)

metrics = MultiprocessInternalPrometheusMetrics(app, path="/api/metrics")

@app.route("/api/v1/ping", methods=["GET"])
def ping():
"""
Simple ping api for health check
:return:
"""
ret = dict()
ret['serviceName'] = 'test'
ret['message'] = 'Healthy'
return jsonify(ret)

if name == 'main':
app.run(host='0.0.0.0', port=8080, processes=10, threaded=False)

**Comment by rycus86** [comment]
Thanks! Do you just run this with Python, or use something like uwsgi to run it?
Also, do you know if the metrics endpoint gets slower by itself or it needs the API endpoints to record metrics?

**Comment by Velan987** [comment]
Running with python only.
After few hours metrics endpoint itself gets slower.
I have configured metrics api with prometheus with scrape interval as 30s.

**Comment by rycus86** [comment]
OK, I'm fairly certain that you're running into this issue from the underlying library: https://github.com/prometheus/client_python/issues/367

It looks like as metrics are recorded, the number of multiprocess-tracked files `PROMETHEUS_MULTIPROC_DIR` directory keep growing and the metrics aggregation becomes slower.
You could raise an issue with them, though there's not seem to be an official recommendation there yet from a quick look.

Based on https://github.com/prometheus/client_python/pull/441#issuecomment-513700380 you could override how the multiprocess pid is being calculated, depending on how you're planning to set you app up.
I can confirm that I could reproduce the gradually slowing metrics endpoint with the https://github.com/rycus86/prometheus_flask_exporter/tree/master/examples/flask-multi-processes example in the repo.
Then I added this snippet from the issue comment linked above to use the _parent process pid_ instead of the current (forked) process pid, and that kept the metrics endpoint latency low as expected:

```python
import os
from prometheus_client import values
values.ValueClass = values.MultiProcessValue(os.getppid)
```

I just dropped this in the main file before the Flask app was initialized.
Let me know if this workaround works for you!

**Comment by Velan987** [comment]
After above code changes I am not seeing that issue, thank you @rycus86 .

**Comment by knwng** [comment]
Hi @rycus86, I wonder will this snippet lead to race condition since now processes forked from the same parent will write to the same file?

**Comment by rycus86** [comment]
Good question! I'm not sure unfortunately, perhaps folks on the prometheus_client issue I linked above would know better?
