### ISSUE TITLE
Compatibility with Counter.count_exceptions()

### ISSUE THREAD

**Issue by Geoiv** [rycus86/prometheus_flask_exporter#45]
I've been using this package with a great degree of success on one of my projects. It's made my life a lot easier! There is one piece of functionality present in the `prometheus_client` package that I haven't been able to replicate with this package, however: Exception counting with `Counter.count_exceptions()`. Is it possible to replicate that functionality within this package, and if so, is there a recommended way of doing so? I've made several attempts to do so myself, but after spending a bit of time on it decided it may be better to reach out here.

Very much appreciate any info you might have on this!

**Comment by rycus86** [comment]
Hi! I'm glad you find this library useful!

Have a look at some error condition handling tests in https://github.com/rycus86/prometheus_flask_exporter/blob/master/tests/test_endpoint.py to see if something like that would help you.
Otherwise, you can use the prometheus_client library to collect metrics. As long as you use the same Registry, this library will expose them on the `/metrics` endpoint.

Does this help?

**Comment by Geoiv** [comment]
Thank you for the quick response, and I apologize for the delay in mine! Yes, that ended up being just what I needed. I very much appreciate the help!
