### ISSUE TITLE
Examples of Prometheus queries

### ISSUE THREAD

**Issue by JackLeo** [rycus86/prometheus_flask_exporter#6]
There should be an example of useful queries with the default data gathered.
Comming to this out of the blue its a bit hard to figure out what should I inspect. For e.g. is this is a right approach?

```
avg(
    (
        flask_http_request_duration_seconds_sum{status='200'} / 
        flask_http_request_duration_seconds_count{status='200'}
    )
) by (endpoint)
```

**Comment by rycus86** [comment]
Thanks for the suggestion!
I think the actual queries need to be tweaked for each application, but I can try to come up with some examples that could be useful in some cases.
The average response time you showed sounds like a good candidate, if there isn't a big spread or large outliers in them, otherwise something like the p90 or p99 metrics could be useful - I think.

I'll try to come up with a few examples and add them to the README.

Thanks!

**Comment by rycus86** [comment]
Hi @JackLeo ,

Collected some examples, and added them as a runnable demo in https://github.com/rycus86/prometheus_flask_exporter/tree/master/examples/sample-signals

Thanks again for raising this issue!
