### ISSUE TITLE
question: is it possible to replace the default histogram with summary?

### ISSUE THREAD

**Issue by yarix** [rycus86/prometheus_flask_exporter#74]
hi
is there an easy way to replace the `flask_http_request_duration_seconds` from HISTOGRAM to SUMMARY?
the default histogram buckets are not appropriate to my use case, and generally histogram should be customized to specific use cases.

from my experience with default Prometheus exporters (in other languages eg. Java/SpringBoot), the basic metric for http is Summary (not Histogram).

thanks

**Comment by rycus86** [comment]
Hi!
There isn't a flag to do that, but you can set `export_defaults=False` then register your own Summary with `register_default`.
Perhaps this could also be a flag in the future, but at the moment it's not available, so you'd need to use this workaround.

**Comment by yarix** [comment]
thanks.

**Comment by rycus86** [comment]
In version `0.16.0` (currently releasing) you can now pass in `default_latency_as_histogram=False` when you create the metrics object to get a summary instead of a histogram for request latencies.

> the default histogram buckets are not appropriate to my use case, and generally histogram should be customized to specific use cases.

Just to circle back to this one, you can override the actual buckets with the `buckets` parameter, though it wasn't documented in the README, but I have added it now.

**Comment by yarix** [comment]
thanks!
