### ISSUE TITLE
Doesn't seem to capture metrics for failed (500) requests?

### ISSUE THREAD

**Issue by mdz** [rycus86/prometheus_flask_exporter#9]
Hi, thanks for sharing this, it seems very close to what I need. My use case is to collect metrics for all requests by status code, for monitoring and alerting. So it's very important that 500s be included in the metrics.

After enabling prometheus_flask_exporter, I get metrics at `/metrics` immediately (yay!) but if I cause an unhandled exception, a 500 is returned to the client, but no metrics are captured. Is this true for others, or just me?

http://flask.pocoo.org/docs/1.0/api/ suggests that `after_request` may not be called in this case, and it looks like that's the hook that the exporter is relying on.

**Comment by rycus86** [comment]
Hi @mdz ,

I think you're right, we do use `after_request`, wasn't aware that it might execute on exceptions. :/
I have a test for this case at https://github.com/rycus86/prometheus_flask_exporter/blob/master/tests/test_endpoint.py#L118, but it looks like either it's one where it's still executed, or the test mode is slightly different in this respect.
Is there any chance you could reproduce your error in a unit test? That would help trying to find a solution to it.
Otherwise some more detailed description would be great.

Thanks!

**Comment by mdz** [comment]
Thanks for the pointer to the unit test, I'll try to reproduce with a minimal case. I suspect it might be related to flask-restful, since it has slightly different error handling behavior.

**Comment by mdz** [comment]
My minimal test cases (https://github.com/basezer0/prometheus_flask_exporter/commit/6d1355cada64b4a0a03670cad9fba227c5f5166a) seem to work fine, so the problem must be in our code somewhere. Sorry for the noise.

**Comment by rycus86** [comment]
No worries! The API docs do indicate that it may not be called in some cases, so it's still possible, maybe it's just that these tests are too *clean* on how they throw the exception - I'm not sure.
Thanks a lot for reporting anyway, if I see it happening again I'll do a deeper investigation.
